# -*- coding: utf-8 -*-
"""Untitled68.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17PBQN94aOlyVDc178FlsJIR0fFN2qjw4
"""

import streamlit as st
import joblib
import pandas as pd
import os

# --- Configuration: File Path ---
MODEL_PATH = 'trained_model (1).joblib'

# --- 1. Load the Model ---
# Caching the model loading for performance
@st.cache_resource
def load_model():
    """Loads the trained model from the joblib file."""
    if not os.path.exists(MODEL_PATH):
        st.error(f"Model file not found at: {MODEL_PATH}. Please ensure the file is in the same directory.")
        return None

    try:
        # Load the scikit-learn model (Pipeline, Classifier, Regressor, etc.)
        model = joblib.load(MODEL_PATH)
        return model
    except Exception as e:
        st.error(f"Error loading model: {e}")
        return None

model = load_model()

# --- 2. Streamlit UI Setup ---
st.set_page_config(page_title="Supply Chain Prediction App", layout="centered")

st.title("📦 Supply Chain Risk Predictor")
st.markdown("Enter the relevant metrics below to predict your supply chain outcome.")

if model is not None:
    # --- 3. User Input Form ---
    st.header("Input Features")

    # NOTE: You must replace 'Feature_A', 'Feature_B', and 'Feature_C'
    # with the actual feature names your model was trained on.
    with st.form("prediction_form"):
        # Example numerical input
        feature_a = st.number_input(
            "Feature A (e.g., Current Inventory Level)",
            min_value=0.0,
            value=50.0,
            step=1.0
        )

        # Example categorical input (will be handled by your Pipeline's preprocessor)
        feature_b = st.selectbox(
            "Feature B (e.g., Supplier Reliability Score)",
            options=[1, 2, 3, 4, 5],
            index=4
        )

        # Example time-related input
        feature_c = st.slider(
            "Feature C (e.g., Expected Lead Time in Days)",
            min_value=1,
            max_value=90,
            value=14
        )

        # Every form must have a submit button
        submit_button = st.form_submit_button("Predict Outcome")

    # --- 4. Prediction Logic ---
    if submit_button:
        # Create a DataFrame from the inputs
        # IMPORTANT: Column names must match the order/names used during model training!
        input_data = pd.DataFrame([[feature_a, feature_b, feature_c]],
            columns=['Feature_A', 'Feature_B', 'Feature_C']
        )

        try:
            # Make the prediction
            prediction = model.predict(input_data)[0]

            st.subheader("Prediction Result:")

            # --- Customize this output based on your model type (classification or regression) ---
            if model.__class__.__name__ in ['Pipeline', 'RandomForestClassifier', 'LogisticRegression']: # Classification Example
                 if prediction == 1:
                     st.success("⚠️ **High Risk of Stock-Out/Disruption**")
                 else:
                     st.info("✅ Low Risk of Disruption")
            else: # Regression Example
                st.metric(label="Predicted Target Value (e.g., Demand Units)", value=f"{prediction:.2f}")

        except Exception as e:
            st.error(f"Prediction failed. Check your input features and model structure: {e}")