# -*- coding: utf-8 -*-
"""Untitled69.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i80TF1yosxCWDOo-7aNOAMj-HF0o3hF5
"""

import streamlit as st
import joblib
import pandas as pd
import os
import traceback # Useful for debugging the version error

# --- Configuration: File Path ---
MODEL_PATH = 'trained_model (1).joblib'
# NOTE: Replace these with the actual feature names your supervised model uses
SUPERVISED_FEATURES = ['Shipment_Volume', 'Supplier_Rating', 'Lead_Time_Days', 'Inventory_Level']


# --- 1. Model Loading Function with Error Handling ---
@st.cache_resource
def load_supervised_model():
    """
    Loads the trained model and includes special handling for scikit-learn version errors.
    """
    st.info(f"Attempting to load supervised model from: {MODEL_PATH}")

    if not os.path.exists(MODEL_PATH):
        st.error(f"Model file not found at: {MODEL_PATH}. Please ensure the file is in the same directory.")
        return None

    try:
        model = joblib.load(MODEL_PATH)
        st.success("Supervised Model loaded successfully!")
        return model

    except AttributeError as e:
        # Check if the error matches the user-reported scikit-learn version issue
        if "_RemainderColsList" in str(e):
            st.error("🚨 Critical Model Loading Error (scikit-learn Version Mismatch!)")
            st.markdown(
                """
                **The model failed to load due to a library version mismatch.**

                The error `Can't get attribute '_RemainderColsList'` means the version of `scikit-learn` used to **save** the model
                is different from the version used to **load** it on Streamlit Cloud.

                **🛠️ Actionable Solution:**
                1. Find the **exact** version of `scikit-learn` you used to train and save the model (e.g., $1.4.2$, $1.3.0$).
                2. Update your `requirements.txt` file to pin this exact version (e.g., `scikit-learn==1.4.2`).
                3. Redeploy your Streamlit app.
                """
            )
        else:
            st.error(f"Error loading model: {e}")
            st.code(traceback.format_exc()) # Show full traceback for other errors

        return None

# Load the supervised model
supervised_model = load_supervised_model()


# --- 2. Streamlit UI Setup ---
st.set_page_config(page_title="Supply Chain ML Solution", layout="wide")

st.title("📦 Robust Supply Chain Predictive Tool")
st.markdown("Solving two critical supply chain problems using Machine Learning.")

# =============================================================================
# Problem 1: Supervised Learning (e.g., Risk Classification)
# =============================================================================
st.header("1. Supervised Learning: Stock-Out Risk Prediction")
st.markdown("Predicts the probability of a critical stock-out or delay based on current metrics ($X$ variables).")

if supervised_model:
    with st.form("supervised_form"):
        st.subheader("Input Features ($X$ variables)")

        # NOTE: Adjust these input widgets to match your SUPERVISED_FEATURES list
        input_data = {}
        input_data['Shipment_Volume'] = st.number_input(
            "Shipment Volume (units)", min_value=1.0, value=100.0, step=10.0
        )
        input_data['Supplier_Rating'] = st.selectbox(
            "Supplier Quality Rating (1=Low, 5=High)", options=[1, 2, 3, 4, 5], index=4
        )
        input_data['Lead_Time_Days'] = st.slider(
            "Expected Lead Time (Days)", min_value=1, max_value=90, value=14
        )
        input_data['Inventory_Level'] = st.number_input(
            "Current Inventory (units)", min_value=0.0, value=500.0, step=50.0
        )

        predict_button = st.form_submit_button("Predict Stock-Out Risk")

    if predict_button:
        # Create a DataFrame for prediction
        input_df = pd.DataFrame([input_data], columns=SUPERVISED_FEATURES)

        try:
            # Make the prediction (Classification Example: 0 or 1)
            prediction = supervised_model.predict(input_df)[0]

            # Predict probability if available, otherwise just use the class
            if hasattr(supervised_model, 'predict_proba'):
                proba = supervised_model.predict_proba(input_df)[0][1] # Probability of the positive class (Risk=1)
                st.subheader("Prediction Result ($Y$ variable)")

                if prediction == 1:
                    st.error(f"⚠️ **HIGH RISK OF STOCK-OUT** (Probability: {proba:.2f})")
                else:
                    st.success(f"✅ Low Risk (Probability: {proba:.2f})")

                st.metric(label="Predicted Risk Score (0 to 1)", value=f"{proba:.2f}")
            else:
                 st.subheader("Prediction Result ($Y$ variable)")
                 risk_label = "HIGH RISK" if prediction == 1 else "LOW RISK"
                 st.metric(label="Predicted Risk Category", value=risk_label)

        except Exception as e:
            st.error(f"Prediction logic failed. Ensure your input columns match the training data: {e}")
            st.code(traceback.format_exc())

# =============================================================================
# Problem 2: Unsupervised Learning (e.g., Anomaly Detection)
# =============================================================================

st.header("2. Unsupervised Learning: Cold Chain Anomaly Detection")
st.markdown("Identifies anomalous data points to flag critical quality issues in real-time (No $Y$ variable needed).")

with st.expander("Demonstrate Unsupervised Anomaly Check"):
    st.warning("This section demonstrates the *result* of a pre-trained Unsupervised Model (e.g., Isolation Forest).")

    col1, col2 = st.columns(2)

    with col1:
        st.subheader("Input ($X$ variables)")
        temp = st.number_input("Sensor Reading: Temperature ($\degree$C)", value=4.5)
        humidity = st.number_input("Sensor Reading: Humidity ($\%$)", value=75.0)
        vibration = st.number_input("Sensor Reading: Vibration (Hz)", value=1.2)

    with col2:
        st.subheader("Model Output (Insight)")
        # Conceptual Unsupervised Logic (replace with actual model code if you had it)
        if temp < 1.0 or temp > 8.0 or vibration > 5.0:
            st.exception("🔥 **CRITICAL ANOMALY DETECTED!**")
            st.markdown(
                """
                **Insight:** Unsupervised model (e.g., Isolation Forest) detected this data point
                as an outlier, likely indicating a cold chain failure or faulty sensor.
                """
            )
        else:
            st.success("No anomaly detected. Data point is within expected clusters/bounds.")